-- ============================================================
-- STORAGE POLICIES — INTENTIONALLY EMPTY
-- ============================================================
--
-- All legacy Supabase Storage policies (references_select_own,
-- references_insert_own, generations_select_own) were dropped in
-- migration 20260326000000_drop_legacy_storage_policies.sql.
--
-- The application exclusively uses Cloudflare R2 for object
-- storage. No Supabase Storage policies are needed.
-- ============================================================
